baseURL = 'http://køkkennoter.dk/'
languageCode = 'da-dk'
defaultContentLanguage = 'da'
title = 'Køkkennoter'

[module]
[[module.imports]]
path = 'github.com/morsby/hugo-book'

[params]
BookTheme = 'light'
BookSection = '*'
BookToC = false